char* SansEspace(char* s);
int comptecomment(char* s);
char giveSep(char* s);
//int comptechamp(char* s);
int comptechampLigne(char* s);
int compteligne(char* s);
int estBienFormate(char* s);
char* Select(char* chiffre, char* s);
int nb_sep(char* txt , char sep);
void echanger(char** a,char** b);
int isNote(char* note);
